services:

# ──────────────────────────────────────────────────────────────
# 1. PostgreSQL 16 (time-zone aware, lightweight Alpine image)
# ──────────────────────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
    ports: ["5432:5432"]
    volumes: 
      - "pgdata:/var/lib/postgresql/data"
      - ".:/workdir"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

# ──────────────────────────────────────────────────────────────
# 2. Envio HyperIndex – Uniswap v4 template (public image)
# ──────────────────────────────────────────────────────────────
  hyperindex:
    build:
      context: ./infra/hyperindex
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: [.env]
    environment:
      - TZ=UTC
    volumes:
      - .:/workdir
      - hyperindex_cache:/root/.envio
    working_dir: /workdir/infra/hyperindex
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || curl -f http://localhost:8080/graphql"]
      interval: 30s
      retries: 5
      start_period: 60s

# ──────────────────────────────────────────────────────────────
# 3. cron (daily refresh)  – runs inside a custom Alpine image
# ──────────────────────────────────────────────────────────────
  refresher:
    build:
      context: .
      dockerfile: Dockerfile.refresher
    restart: unless-stopped
    depends_on:
      - hyperindex
    volumes: [.:/workdir]

volumes:
  pgdata:          # durable Postgres storage
  hyperindex_cache: # optional: keeps ABI + block-cache across restarts
