# HyperIndex config for UniChain WBTC/ETH swap indexing
# Tracks only the two specified pools: hooked (AEGIS_DFM) and static

name: unichain-wbtc-eth-swaps
description: "Indexes WBTC/ETH swaps from hooked and static pools on UniChain"

contracts:
  - name: PoolManager
    handler: infra/hyperindex/mappings.ts
    events:
      - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee)

networks:
  - id: 11877 # unichain
    start_block: 18650793
    rpc: ${RPC_URL}
    contracts:
      - name: PoolManager
        address:
          - "0x1f98400000000000000000000000000000000004" # The address you provided

# Database configuration
